name: Linting, Formatting and Testing Checks

description: 'Runs prettier, linting and testing'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js and Install Dependencies
      uses: ./.github/setup-node-dependencies

    - name: Run ESLint
      run: npm run lint
      shell: bash

    - name: Run Prettier
      run: npm run prettier:check
      shell: bash

    - name: Run tests
      run: npm run test
      shell: bash
