name: CD Bookstore

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }} and Install Dependencies
        uses: ./.github/setup-node-dependencies
        with:
          node-version: ${{ matrix.node-version }}

      - name: Linting, Formatting and Testing Checks
        uses: ./.github/checks
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy
        run: echo "Deploying... (Coming in later sessions)"
