name: CI/CD Bookstore

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/setup-node-dependencies

      - name: Linting, Formatting and Testing Checks
        uses: ./.github/checks

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/setup-node-dependencies

      - name: Linting, Formatting and Testing Checks
        uses: ./.github/checks

      - name: Deploy
        run: echo "Deploying... (Coming in later sessions)"
