name: CI Bookstore

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/setup-node-dependencies
        with:
          node-version: '20'

      - name: Linting, Formatting and Testing Checks
        uses: ./.github/checks
