name: Build Docker Image

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: main

    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and Install Dependencies
        uses: ./.github/workflows/actions/setup
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.ROLE_NAME }}
          aws-region: ${{ vars.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

    - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: bookstore-api
          path: /tmp

      - name: Load Docker Image
        run: |
          IMAGE_TAG=latest
          docker load -i /tmp/bookstore-api.tar
          docker tag bookstore-api:$IMAGE_TAG ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG
